### ISSUE TITLE
本机运行server跟client开100个,异步.客户端服务器都崩了

### ISSUE THREAD

**Issue by a11s** [issingle/kcp.net#1]
服务器 
throw new ArgumentNullException("array");

>   KCP.dll!KCP.Common.DefaultArrayPool<byte>.Return(byte[] array, bool clearArray) 行 305 C#
>     KCP.dll!KCP.Server.KCPServer..ctor.AnonymousMethod__21_1(byte[] buf) 行 68 C#
>     KCP.dll!KCP.Common.KCPLib.Dispose() 行 1173    C#
>     KCP.dll!KCP.Server.KCPServer.ProcessDisposedQueue() 行 143 C#
>     KCP.dll!KCP.Server.KCPServer.Update() 行 122   C#
>     teste_kcp_server.exe!Program.Main(string[] args) 行 31 C#

客户端Assert
Debug.Assert(c.EndPoint.ToString() == e.RemoteEndPoint.ToString());
两者端口不同

**Comment by issingle** [comment]
这个端口不同是很有可能的。这个Asset只是用于调试。
